title: Charles Averill
description: A page to display my cool projects
theme: jekyll-theme-cayman
google_analytics: G-WQRMTEBTKE
output:
  html_document:
    includes:
      in_header: analytics.html
